prose:
	rooturl: 'home'
	siteurl: 'http://db.deveel.org'
	relativeLinks: 'http://db.deveel.org/links.jsonp'
	media: 'media'
	  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes